name: Build

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven
    
    - name: Build
      run: mvn -B compile --file pom.xml
    
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: build/libs/*.jar
