name: Build

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Gradle Wrapper
        run: gradle wrapper

      - name: Build
        run: ./gradlew build

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: build/libs/*.jar
